apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    olm.providedAPIs: TektonAddon.v1alpha1.operator.tekton.dev,TektonChain.v1alpha1.operator.tekton.dev,TektonConfig.v1alpha1.operator.tekton.dev,TektonHub.v1alpha1.operator.tekton.dev,TektonInstallerSet.v1alpha1.operator.tekton.dev,TektonPipeline.v1alpha1.operator.tekton.dev,TektonTrigger.v1alpha1.operator.tekton.dev
  name: global-operators
  namespace: openshift-operators
