apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
    monitoring-key: djl-grafana
  name: app-services
spec:
  endpoints:
    - interval: 5s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - user1-flying-djl
  selector:
    matchLabels:
      monitoring: prometheus
