apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: minio
spec:
  port:
    targetPort: console
  tls:
    termination: edge
  to:
    kind: Service
    name: minio
  wildcardPolicy: None
